### ISSUE TITLE
Not compatible with FluentAssertions 5.0+

### ISSUE THREAD

**Issue by wingfaic** [benagain/NSubstitute.Verify.That#1]
Hi there, I'm trying to use your library with .net core 2.1 project that depends on FluentAssertions 5.0+ and it looks like it just causes the test to fail 100% of the time with NSubstitute thinking there's no matching calls.

However if I bring the Verify class into the project it seems to work perfectly fine.  Feels like a weird .net dependency issue.

Are there any plans to update to 5.0+ of FluentAssertions?

**Comment by benagain** [comment]
Hi @wingfaic,  I haven't used this is a while but I'll have a quick look this week to see what I can do.  

Could you put a gist up that I could use to reproduce the problem?  Thanks!

**Comment by wingfaic** [comment]
@benagain Here's the repro
https://gist.github.com/wingfaic/4ef0c52cc0c9259849559808d81fac92

**Comment by benagain** [comment]
That's great thanks!  You're right in that it's a problem with `FluentAssertions` 5.0 and above, everything else updated fine and still worked.  5.0 was a major version increment after all!

I've rebuilt `NSubstitute.Verify.That` against `FluentAssertions` 5.0, and taken the opportunity to update to `netstandard2.0` at the same time.  It seems to be fine now against your repro, and my own tests.  I've published as a pre-release for now just to get your feedback: https://www.nuget.org/packages/NSubstitute.Verify.That/2.0.0-beta.  Could you let me know if that works OK and I'll make it official.

Thanks for the issue :smile:

**Comment by wingfaic** [comment]
@benagain I just tested it and it looks great! 👍

**Comment by benagain** [comment]
Excellent, thanks for letting me know, I've published it as v2.0.0 now too.
