### ISSUE TITLE
TypeLoadException for ArgumentSpecificationQueue 

### ISSUE THREAD

**Issue by AbbasKhalili** [benagain/NSubstitute.Verify.That#2]
I use FluentAssertions 5.6 and NSubstitute 4.1, but there is exception about type loading. 

System.TypeLoadException: Could not load type 'NSubstitute.Core.Arguments.ArgumentSpecificationQueue' from assembly 'NSubstitute, Version=4.1.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca'.
   at NSubstitute.Verify.That[T](Action`1 action)

**Comment by benagain** [comment]
Hi,

It looks like a breaking change in NSubstitute between 3.x and 4.x - https://github.com/nsubstitute/NSubstitute/blob/master/BreakingChanges.md#400-release.

If I have some time I'l update the library soon.

**Comment by AbbasKhalili** [comment]
use this :

public static class Inquire
    {
        private static readonly ArgumentFormatter DefaultArgumentFormatter = new ArgumentFormatter();
        public static T That<T>(Action<T> action)
        {
            return ArgumentMatcher.Enqueue<T>(new AssertionMatcher<T>(action));
        }
        private class AssertionMatcher<T> : IArgumentMatcher<T>, IDescribeNonMatches
        {
            private readonly Action<T> assertion;
            private string allFailures = "";
            private bool lastResult = false;
            private bool hasRunBefore = false;
            public AssertionMatcher(Action<T> assertion)
            {
                this.assertion = assertion;
            }

            public bool IsSatisfiedBy(T argument)
            {
                if (hasRunBefore) return lastResult;

                using (var scope = new AssertionScope())
                {
                    try
                    {
                        assertion(argument);
                    }
                    catch (Exception exception)
                    {
                        var f = scope.Discard();
                        allFailures = f.Any() ? AggregateFailures(f) : exception.Message;

                        return SetResult(false);
                    }

                    var failures = scope.Discard().ToList();

                    if (failures.Count == 0) return SetResult(true);

                    allFailures = AggregateFailures(failures);

                    return SetResult(false);
                }
            }

            private bool SetResult(bool result)
            {
                this.hasRunBefore = true;
                this.lastResult = result;
                return result;
            }

            private string AggregateFailures(IEnumerable<string> discard)
                => discard.Aggregate(allFailures, (a, b) => a + "\n" + b);

            public string DescribeFor(object argument)
            {
                return DefaultArgumentFormatter.Format(allFailures, false);
            }
        }
    }

**Comment by rklec** [comment]
This still happens:
> System.TypeLoadException : Could not load type 'NSubstitute.Core.Arguments.ArgumentSpecificationQueue' from assembly 'NSubstitute, Version=4.4.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca'.
   at NSubstitute.Verify.That[T](Action`1 action)
   
```c#
await this.someSerializer.ReceivedWithAnyArgs(1)
                .SerializeToCsv(Verify.That<IList<SomeExportModel>>(x =>
                        x.Should().BeEquivalentTo(new List<SomeExportModel>()
                            {
                                new() { SomeProperty = activeObject.SomeProperty }
                            }
                        )
                    )
                );
````

v2.0.0
